### PR TITLE
Generate initial .pot file so people doing translations can start working.

### PR DESCRIPTION
**Pull request by rudigiesler**

### CODE REVIEW

**Comment by rudigiesler** [comment]
Going to extend this issue to include adding the translations that we have.

**Comment by rudigiesler** [comment]
@hodgestar ready for review

**Comment by hodgestar** [comment]
I like to put the generated files in a `translations` folder because there can be quite a lot of them potentially (different domains, different languages, etc).

**Comment by hodgestar** [comment]
Otherwise looks good.

**Comment by rudigiesler** [comment]
@hodgestar Moved the translations files into `translations`

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
