### PR TITLE
two ona submissions for new forms

### PR DESCRIPTION
**Pull request by rudigiesler**

### CODE REVIEW

**Comment by hodgestar** [comment]
I'm trying to decide whether we really want to remove the GPS jitter? The toilets within a unit will still have the same GPS location and we'll still want to scatter the reports somewhat so they can all easily be seen?

**Comment by rudigiesler** [comment]
I wasn't sure what the full purpose of the form is? It will only be used by internal people, so I thought it might be used as a listing of all the reports submitted and their status, but I guess that's what Snappy is for, not Ona.

I'll put the jitter back in, but how will this report be used?

**Comment by hodgestar** [comment]
The per_report form is still meant to provide a map of reports -- they'll
just be private so that we can include phone numbers, etc. I think that
means we still want to jitter them so that admins can see them on the map?

**Comment by rudigiesler** [comment]
@hodgestar GPS jitter has been added back in

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
