### PR TITLE
update screen text

### PR DESCRIPTION
**Pull request by rudigiesler**
Update the text according to:

https://praekelt.slack.com/files/laurenk/F02LMHC42/imali_yethu_pilot_copy_v1.xlsx

### CODE REVIEW

**Comment by rudigiesler** [comment]
Latest text found here:

https://docs.google.com/a/praekeltconsulting.com/spreadsheets/d/1XEwY8QvY6uKuYDDzBE4t-fPA-S8LYdQrfB0m05TNMKw/

**Comment by rudigiesler** [comment]
@hodgestar ready for review

**Comment by hodgestar** [comment]
:+1:

I would have spelled "Call" with a lower-case "c" -- perhaps we should check that with Lauren?

**Comment by rudigiesler** [comment]
It was just copied straight out of the google doc, I'll check it with Lauren before merging.

**Comment by hodgestar** [comment]
Happy for us to merge this and just update the "c" later if needed.

**Pull request merged**
