### PR TITLE
Add language to the text sent to Snappy.

### PR DESCRIPTION
**Pull request by hodgestar**

### CODE REVIEW

**Comment by hodgestar** [comment]
Ready for review.

**Comment by hodgestar** [comment]
@rudigiesler @neytiri

**Comment by rudigiesler** [comment]
:+1: when travis is happy

**Comment by neytiri** [comment]
Just checking if this is in QA or live? I couldn't see the change in snappy. Thanks :)

**Comment by neytiri** [comment]
oh arg sorry was looking at old tickets. Checked now to see if I can see it when I send a new report and its there. yay thank you!

**Comment by hodgestar** [comment]
It should be live. :)

I saw the "Language: en" in the latest Snappy email.

**Pull request merged**
