### PR TITLE
clean up ona migration script folder

### PR DESCRIPTION
**Pull request by rudigiesler**

### CODE REVIEW

**Comment by rudigiesler** [comment]
Ready for review, although I'm unsure if this new setup will be testing all node and all python versions.

**Comment by hodgestar** [comment]
Apparently it's only running with Node 0.10, although I'm not entirely sure why though. Everything else looks good though.

**Comment by rudigiesler** [comment]
I think because I changed `language` from `node_js` to `python`, it's not actually testing node things anymore. It's just abusing the fact that travis has node 0.10 installed by default. I'm not sure how to solve it, it seems like travis cannot handle 2 different languages: https://groups.google.com/forum/#!topic/travis-ci/3pzCgvxWZAo

**Comment by hodgestar** [comment]
Maybe we can do something with
http://docs.travis-ci.com/user/build-configuration/#Explicit-inclusion-of-jobs-into-the-build-matrix
?

E.g. remove the node_js lines and add:

```
matrix:
  include:
    - python: 2.7
      node_js: 0.11
    - python: 3.4
      node_js: 0.11
```

?

**Comment by rudigiesler** [comment]
Build matrix doesn't seem to help. When looking at the build table it shows different node versions, but looking at the build log it stays at node v0.10

**Comment by rudigiesler** [comment]
I think I have a solution, involving environment variables controlling which tests get run and which version of node is used, I'll have to try it out first though.

**Comment by rudigiesler** [comment]
@hodgestar Ready for you to have a look, I'm quite sure it's running tests properly for node and python now.

**Comment by hodgestar** [comment]
:+1:

I think there might be better ways to organize the Travis setup, but I think this is enough bikeshedding for this PR. :)

**Pull request merged**
